version: "3"
services:
  redis_pubsub:
    image: sensorhub:v0.1.0
    environment:
      - DB_HOST=postgres-prod
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - PYTHONDONTWRITEBYTECODE=1
    entrypoint:
      - python
      - /src/sensorprocessor/entrypoints/redis_eventconsumer.py
    networks:
      - sensorhub

  api:
    image: sensorhub:v0.1.0
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - API_HOST=${API_HOST}
      - REDIS_HOST=${REDIS_HOST}
      - PYTHONDONTWRITEBYTECODE=1
      - FLASK_APP=sensorprocessor/entrypoints/flask_app.py
      - PYTHONUNBUFFERED=1
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
      - --port=80
    ports:
      - "5005:80"
    networks:
      - sensorhub

networks:
  sensorhub:
    external: true
