version: "3"
services:
  redis_pubsub:
    build:
      context: .
      dockerfile: Dockerfile
    image: sensorhub
    depends_on:
      - redis
      - postgres
    env_file:
      - ./.env.prod
    entrypoint:
      - python
      - /src/sensorprocessor/entrypoints/redis_eventconsumer.py
    networks:
      - sensorhub

  api:
    image: sensorhub
    depends_on:
      - redis_pubsub
      - postgres
    env_file:
      - ./.env.prod
    entrypoint:
      - gunicorn
      - --workers=4
      - --bind=0.0.0.0:5000
      - sensorprocessor.entrypoints.flask_app:app
    expose:
      - 5000
    networks:
      - sensorhub

  postgres:
    image: postgres:16.2
    env_file:
      - ./.env.prod
    ports:
      1433:1433
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    networks:
      - sensorhub

  redis:
    image: redis:alpine
    ports:
     - 6379:6379
    networks:
     - sensorhub

  nginx:
    build: ./nginx
    ports:
     - 1337:80
    depends_on:
     - api
    networks:
     - sensorhub

volumes:
  postgres_data_prod:

networks:
  sensorhub:
