"""Initial

Revision ID: b6c369b2a36b
Revises: 
Create Date: 2024-05-07 18:44:32.147726

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6c369b2a36b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "current_data_view",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("sensor", sa.String(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("sensor"),
    )
    op.create_table(
        "sensordata",
        sa.Column("sensor", sa.String(), nullable=False),
        sa.Column("version_number", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("sensor"),
    )
    op.create_table(
        "rawdata",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sensor", sa.String(), nullable=True),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sensor"],
            ["sensordata.sensor"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rawdata")
    op.drop_table("sensordata")
    op.drop_table("current_data_view")
    # ### end Alembic commands ###
